### ISSUE TITLE
content inside code box overflows

### ISSUE THREAD

**Issue by mattmezza** [daleanthony/uno#20]
Especially when rendering mobile layout, source code is likely to overflow the code box. 
This causes the layout to not render properly.
![issue](https://cloud.githubusercontent.com/assets/1915989/3046848/0d004734-e12e-11e3-846d-a7b85970a01c.png)
Probably an `overflow-x: scroll;` property for the code tag may solve this problem.
https://github.com/mattmezza/Uno/commit/e500463d744db83da35a1640b17b9286c288d55f

**Comment by howdydoody123** [comment]
This also happens on desktop.

![](http://i.imgur.com/pD3LkjH.png)

**Comment by mattmezza** [comment]
Got no time to make a pull request, but [this commit](https://github.com/mattmezza/Uno/commit/e500463d744db83da35a1640b17b9286c288d55f) should do the trick...
