### ISSUE TITLE
Previous/Next post buttons

### ISSUE THREAD

**Issue by howdydoody123** [daleanthony/uno#21]
Feature Request

Add buttons at the bottom of posts to allow for navigating to prior or next post on the blog

**Comment by howdydoody123** [comment]
Just noticed that this is a feature which will be added in the 0.8 release

**Comment by cyrusdavid** [comment]
Why the close if not yet implemented?

**Comment by mattmezza** [comment]
Because this is a feature that will probably be released in the 0.8 version of ghost. At the moment ghost's API does not provide the information on which this feature request issue relies to be implemented. I think this is the reason of the close ;-)

**Comment by howdydoody123** [comment]
That is exactly the reason. Ghost plans to add this feature in the 0.8 release. I originally was under the impression this is something a theme programmer would add manually

**Comment by cyrusdavid** [comment]
Oh, right! Forgive me.
