### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by unwitting** [daleanthony/uno#3]
Uno's a gorgeous theme, I'm running it on my in-development Ghost blog and love it. What (if any) licensing do you have on the theme? Could they be included in the repository to clarify to anyone interested in forking / contributing etc?

**Comment by unwitting** [comment]
Is there an update on this? Are you still actively monitoring this repo?

**Comment by ibrahimyu** [comment]
+1. Unclear license kept me from using this theme.

**Comment by daleanthony** [comment]
@unwitting @ibrahimyu Sorry it's taken me a while to reply chaps! I've just updated the README file with licence details (Creative Commons Attribution 4.0 International).

**Comment by unwitting** [comment]
Nice, thankyou very much :D
